#!/bin/sh

THEMES_DIR="$HOME/.config/qtile/themes"
CONFIG_FILE="$HOME/.config/.theme/config.json"

themes=$(ls "$THEMES_DIR" | sed 's/\.json$//')

selected_theme=$(echo "$themes" | rofi -dmenu -p "Select a theme")

if [ -n "$selected_theme" ]; then
    # Change the theme on the config file
    jq --arg theme "$selected_theme" '.theme = $theme' "$CONFIG_FILE" > "${CONFIG_FILE}.tmp" && mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"

    # APPLY THEME ON APPLICATIONS
    # Restart Qtile to apply theme on Qtile
    qtile cmd-obj -o cmd -f restart
fi